apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: lidiyahanicheva/my-flask-app:latest
          ports:
            - containerPort: 9090
          env:
            # - name: MONGO_URI
            #   value: "mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@mongo:27017/$(MONGO_DB_NAME)"
            - name: MONGO_HOST
              value: "mongo.default.svc.cluster.local"
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: MONGO_DB_NAME
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: FLASK_SERVER_PORT
              value: "9090"
      restartPolicy: Always
